name: pytmle-sim
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - numpy
  - pandas
  - scipy
  - pyyaml
  - pyarrow
  - scikit-learn
  - matplotlib
  - seaborn
  - pytest
  - ipykernel
  - r-base
  - r-survival
  - r-jsonlite
  - r-renv
  - r-remotes
  - r-riskregression
  - r-adjustedcurves
  - r-arrow
  - r-devtools
  - c-compiler
  - cxx-compiler
  - make
  - pkg-config
  - pip:
      - torch
      - pycox
      - scikit-survival
      - mlflow
      - tqdm
      - sqlparse
      - cloudpickle<4
      - sqlalchemy
      - itsdangerous
      - markupsafe
      - werkzeug
      - smmap
      - zipp
      - gunicorn
      - ply
      - texttable
      - numba
      - prettytable
      - filelock
      - fsspec